package com.mycompany.horticultores;

import javax.swing.JOptionPane;

/**
 *
 * @author mezti
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        altasHorticultores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        folio = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        domicilio = new javax.swing.JTextField();
        noIfe = new javax.swing.JTextField();
        imagen = new javax.swing.JTextField();
        tamañoParcela = new javax.swing.JTextField();
        botonGuardarHorticultores = new javax.swing.JButton();
        botonSalirHorticultores = new javax.swing.JButton();
        altasFlores = new javax.swing.JPanel();
        folioFlores = new javax.swing.JLabel();
        tipoFlores = new javax.swing.JLabel();
        folioFloresText = new javax.swing.JTextField();
        listaFlores = new javax.swing.JComboBox<>();
        botonGuardarFlores = new javax.swing.JButton();
        botonSalirFlores = new javax.swing.JButton();
        altasSegmentacion = new javax.swing.JPanel();
        botonGuardarSegmentacion = new javax.swing.JButton();
        botonSalirSegmentacion = new javax.swing.JButton();
        folioSegmentacion = new javax.swing.JTextField();
        segmentacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        altasHorti = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        botonAltasFlores = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        botonAltasSegmentacion = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Cooperativa de Horticultores");

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel9)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel9)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        altasHorticultores.setVisible(false);

        jLabel1.setText("No de folio: ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Apellidos: ");

        jLabel4.setText("Edad:");

        jLabel5.setText("Domicilio: ");

        jLabel6.setText("No IFE:  ");

        jLabel7.setText("Imagen: ");

        jLabel8.setText("Tamaño parcela: ");

        botonGuardarHorticultores.setText("Guardar");
        botonGuardarHorticultores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarHorticultoresActionPerformed(evt);
            }
        });

        botonSalirHorticultores.setText("Salir");
        botonSalirHorticultores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirHorticultoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout altasHorticultoresLayout = new javax.swing.GroupLayout(altasHorticultores);
        altasHorticultores.setLayout(altasHorticultoresLayout);
        altasHorticultoresLayout.setHorizontalGroup(
            altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasHorticultoresLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altasHorticultoresLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(botonSalirHorticultores))
                    .addGroup(altasHorticultoresLayout.createSequentialGroup()
                        .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonGuardarHorticultores)
                                .addComponent(jLabel8)))
                        .addGap(37, 37, 37)
                        .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noIfe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tamañoParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        altasHorticultoresLayout.setVerticalGroup(
            altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasHorticultoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noIfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamañoParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(altasHorticultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarHorticultores)
                    .addComponent(botonSalirHorticultores))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        altasFlores.setVisible(false);

        folioFlores.setText("Folio");

        tipoFlores.setText("Tipo de flor: ");

        folioFloresText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioFloresTextActionPerformed(evt);
            }
        });

        listaFlores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alcatráz", "Aretillo", "Azalea", "Clavel", "Cempaxúchitl", "Dalia", "Flor de calavaza", "Floripondio", "Gladiola", "Girasol", "Clavelina", "Mercadela", "Flor de chícharo", "Estátil", "Otras" }));
        listaFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFloresActionPerformed(evt);
            }
        });

        botonGuardarFlores.setText("Guardar");
        botonGuardarFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarFloresActionPerformed(evt);
            }
        });

        botonSalirFlores.setText("Salir");
        botonSalirFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirFloresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout altasFloresLayout = new javax.swing.GroupLayout(altasFlores);
        altasFlores.setLayout(altasFloresLayout);
        altasFloresLayout.setHorizontalGroup(
            altasFloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altasFloresLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(altasFloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(altasFloresLayout.createSequentialGroup()
                        .addComponent(tipoFlores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(listaFlores, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(altasFloresLayout.createSequentialGroup()
                        .addComponent(folioFlores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(folioFloresText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, altasFloresLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonGuardarFlores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalirFlores)
                        .addGap(17, 17, 17)))
                .addGap(89, 89, 89))
        );
        altasFloresLayout.setVerticalGroup(
            altasFloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasFloresLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(altasFloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folioFlores)
                    .addComponent(folioFloresText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(altasFloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaFlores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoFlores))
                .addGap(66, 66, 66)
                .addGroup(altasFloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarFlores)
                    .addComponent(botonSalirFlores))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        altasSegmentacion.setVisible(false);

        botonGuardarSegmentacion.setText("Guardar");
        botonGuardarSegmentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarSegmentacionActionPerformed(evt);
            }
        });

        botonSalirSegmentacion.setText("Salir");
        botonSalirSegmentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirSegmentacionActionPerformed(evt);
            }
        });

        jLabel10.setText("Folio: ");

        jLabel11.setText("Segmentación: ");

        javax.swing.GroupLayout altasSegmentacionLayout = new javax.swing.GroupLayout(altasSegmentacion);
        altasSegmentacion.setLayout(altasSegmentacionLayout);
        altasSegmentacionLayout.setHorizontalGroup(
            altasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasSegmentacionLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(altasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(altasSegmentacionLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(103, 103, 103)
                        .addComponent(folioSegmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(altasSegmentacionLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(53, 53, 53)
                        .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(altasSegmentacionLayout.createSequentialGroup()
                        .addComponent(botonGuardarSegmentacion)
                        .addGap(73, 73, 73)
                        .addComponent(botonSalirSegmentacion)
                        .addGap(27, 27, 27)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        altasSegmentacionLayout.setVerticalGroup(
            altasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altasSegmentacionLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(altasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folioSegmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(56, 56, 56)
                .addGroup(altasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(68, 68, 68)
                .addGroup(altasSegmentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarSegmentacion)
                    .addComponent(botonSalirSegmentacion))
                .addGap(86, 86, 86))
        );

        jMenu1.setText("Horticultores");

        altasHorti.setText("Altas");
        altasHorti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasHortiActionPerformed(evt);
            }
        });
        jMenu1.add(altasHorti);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Flores");

        botonAltasFlores.setText("Altas");
        botonAltasFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltasFloresActionPerformed(evt);
            }
        });
        jMenu2.add(botonAltasFlores);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Segmentación");

        botonAltasSegmentacion.setText("Altas");
        botonAltasSegmentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltasSegmentacionActionPerformed(evt);
            }
        });
        jMenu4.add(botonAltasSegmentacion);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altasHorticultores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(altasFlores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(altasSegmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(altasHorticultores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(altasFlores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(altasSegmentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAltasFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltasFloresActionPerformed
        altasFlores.setVisible(true);
        altasHorticultores.setVisible(false);
        altasSegmentacion.setVisible(false);
        inicio.setVisible(false);
    }//GEN-LAST:event_botonAltasFloresActionPerformed

    private void botonGuardarHorticultoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarHorticultoresActionPerformed
        JOptionPane.showMessageDialog(altasHorticultores, "Se guardó exitosamente");
    }//GEN-LAST:event_botonGuardarHorticultoresActionPerformed

    private void altasHortiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasHortiActionPerformed
        altasHorticultores.setVisible(true);
        altasFlores.setVisible(false);
        inicio.setVisible(false);
        altasSegmentacion.setVisible(false);
    }//GEN-LAST:event_altasHortiActionPerformed

    private void botonSalirHorticultoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirHorticultoresActionPerformed
        JOptionPane.showMessageDialog(altasHorticultores, "El usuario María Raquel Martínez Urrutia va a salir");
    }//GEN-LAST:event_botonSalirHorticultoresActionPerformed

    private void folioFloresTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioFloresTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folioFloresTextActionPerformed

    private void listaFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFloresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaFloresActionPerformed

    private void botonGuardarFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarFloresActionPerformed
        JOptionPane.showMessageDialog(altasFlores, "Se guardó POO2 ES202107345");
    }//GEN-LAST:event_botonGuardarFloresActionPerformed

    private void botonSalirFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirFloresActionPerformed
        JOptionPane.showMessageDialog(altasFlores, "Salir ES202107345");
    }//GEN-LAST:event_botonSalirFloresActionPerformed

    private void botonAltasSegmentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltasSegmentacionActionPerformed
        altasSegmentacion.setVisible(true);
        altasHorticultores.setVisible(false);
        altasFlores.setVisible(false);
        inicio.setVisible(false);
    }//GEN-LAST:event_botonAltasSegmentacionActionPerformed

    private void botonGuardarSegmentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarSegmentacionActionPerformed
        JOptionPane.showMessageDialog(altasSegmentacion, "Se guardó en la base de datos");
    }//GEN-LAST:event_botonGuardarSegmentacionActionPerformed

    private void botonSalirSegmentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirSegmentacionActionPerformed
        JOptionPane.showMessageDialog(altasSegmentacion, "Correo: dl13coqa0127.amadeo@nube.unadmexico.mx");
    }//GEN-LAST:event_botonSalirSegmentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel altasFlores;
    private javax.swing.JMenuItem altasHorti;
    private javax.swing.JPanel altasHorticultores;
    private javax.swing.JPanel altasSegmentacion;
    private javax.swing.JTextField apellidos;
    private javax.swing.JMenuItem botonAltasFlores;
    private javax.swing.JMenuItem botonAltasSegmentacion;
    private javax.swing.JButton botonGuardarFlores;
    private javax.swing.JButton botonGuardarHorticultores;
    private javax.swing.JButton botonGuardarSegmentacion;
    private javax.swing.JButton botonSalirFlores;
    private javax.swing.JButton botonSalirHorticultores;
    private javax.swing.JButton botonSalirSegmentacion;
    private javax.swing.JTextField domicilio;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField folio;
    private javax.swing.JLabel folioFlores;
    private javax.swing.JTextField folioFloresText;
    private javax.swing.JTextField folioSegmentacion;
    private javax.swing.JTextField imagen;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> listaFlores;
    private javax.swing.JTextField noIfe;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField segmentacion;
    private javax.swing.JTextField tamañoParcela;
    private javax.swing.JLabel tipoFlores;
    // End of variables declaration//GEN-END:variables
}
